version: "3.8"

services:
  mariadb:
    build: ./requierments/mariadb/.
    container_name: mariadb_container
    volumes:
      - mdb:/var/lib/mysql
    expose:
        - "3306"
    env_file:
      - ../.env
    networks:
      - docker-network
    restart: on-failure

  wordpress:
    build: ./requierments/wordpress/.
    container_name: wordpress_container
    # ports:
    #   - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - docker-network
    expose:
      - "9000"
    restart: on-failure

  nginx:
    build: ./requierments/nginx/.
      # context: ./requierments/nginx/.
      # args:
      #   DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: nginx_container
    ports:
      - 443:443
    env_file:
      - ../.env
    # volumes:
    #   - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: on-failure

volumes:
  mdb:
   driver_opts:
      type: 'none'
      o: bind
      # MacOS: 
      device: /Users/christian.rasche/crasche/data/mysql
      # Linux:
      # device: /home/crasche/data/mysql
  wp:
   driver_opts:
      type: 'none'
      o: bind
      # MacOS: 
      device: /Users/christian.rasche/crasche/data/wordpress
      # Linux:
      # device: /home/crasche/data/wordpress
networks:
    docker-network:
        driver: bridge