version: "3.8"

services:
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    container_name: mariadb
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    env_file:
      - ../.env
    networks:
      - docker-network
    expose:
      - "3306"

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www/html
    networks:
      - docker-network
    env_file:
      - ../.env
    expose:
      - "9000"
    restart: on-failure

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    env_file:
      - ../.env
    volumes:
      - wp-volume:/var/www/html:ro
      - ./requirements/nginx/conf:/etc/nginx/conf.d/
    depends_on:
      - wordpress
    networks:
      - docker-network
    restart: on-failure

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # MacOS:
      # device: /Users/christian.rasche/crasche/data/mariadb
      # Linux:
      device: /home/crasche/data/mariadb
  wp-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # MacOS:
      # device: /Users/christian.rasche/crasche/data/wordpress
      # Linux:
      device: /home/crasche/data/wordpress

networks:
    docker-network:
        driver: bridge